---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule yamllint ansible-lint docker

script:
  - molecule test
