---
# tasks file for JacksonCampolattaro.vim

- name: Install NeoVim
  package:
          name: neovim
          state: latest
  become: true

  #- name: Install NeoVim Python host
  #  pip:
  #          name: neovim
  #          state: latest

- name: Install NeoVim Python host
  pip:
          name: neovim
          state: latest
          extra_args: --user
  

- name: Configure NeoVim dotfiles
  copy:
          src: nvim
          dest: ~/.config/

- name: Install Vim-Plug
  git:
          repo: https://github.com/junegunn/vim-plug.git
          dest: ~/.local/share/nvim/site/autoload/
          depth: 1

- name: Install plugins
  shell: >
          nvim
          +PlugInstall
          +UpdateRemotePlugins
          +qall!

          #- name: Use Vim-Plug to install plugins
          #  shell: nvim --headless +PlugInstall +qall > /dev/null
          #  changed_when: false
