---
# tasks file for JacksonCampolattaro.vim

- name: Install NeoVim
  package:
          name: neovim
          state: latest
  become: true

- name: Configure NeoVim dotfiles
  copy:
          src: nvim
          dest: ~/.config/

- name: Install Vim-Plug
  git:
          repo: https://github.com/junegunn/vim-plug.git
          dest: ~/.local/share/nvim/site/autoload/
          depth: 1

- name: Install plugins automatically
  command: vim +PlugInstall +qall
