---
# tasks file for JacksonCampolattaro.vim

- name: Install NeoVim
  package:
          name: neovim
          state: latest
  become: true

- name: Configure NeoVim dotfiles
  copy:
          src: nvim
          dest: ~/.config/nvim
