---
# tasks file for JacksonCampolattaro.vim

- name: Install NeoVim
  package:
          name: neovim
          state: latest
  become: true

- name: Install NeoVim Python host
  pip:
          name: neovim
          state: latest
          extra_args: --user
  
- name: Pull NeoVim dotfiles from git
  git:
          repo: https://github.com/JacksonCampolattaro/dotfiles-vim.git
          dest: ~/.config/nvim
          update: true

- name: Install Vim-Plug
  git:
          repo: https://github.com/junegunn/vim-plug.git
          dest: ~/.local/share/nvim/site/autoload/
          depth: 1

- name: Use Vim-Plug to install plugins
  shell: nvim --headless +PlugInstall +UpdateRemotePlugins +qall > /dev/null
  changed_when: false
